# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180727_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensee',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='expensee',
            name='amount3',
        ),
    ]
